backend:
  name: github
  repo: arizonainlove/trantamcapital
  branch: main
  auth_type: implicit

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: "news"
    label: "News Articles"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Category", name: "category", widget: "select", options: ["Cryptocurrency", "Forex", "Binary Options", "Markets"] }
      - { label: "Author", name: "author", widget: "string", default: "TrantamCapital" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", pattern: ["^.{10,}$", "Must be at least 10 characters"] }
      - { label: "Body", name: "body", widget: "markdown" }
