backend:
  name: github
  repo: arizonainlove/trantamcapital
  branch: main
  base_url: https://protradevision.com
  auth_endpoint: api/auth

collections:
  - name: "news"
    label: "News Articles"
    folder: "trantamcapital/src/content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
